name: Daily Commit

on:
  schedule:
    - cron: '53 10 * * *'
  workflow_dispatch:


jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update file
        run: |
          echo "Updated on $(date)" >> contributions.txt
      - name: Commit changes
        run: |
          git config user.name "josiahprime"
          git config user.email "choujiakimichi02@gmail.com"
          git add contributions.txt
          git commit -m "Daily update $(date)" || echo "No changes"
          git push
